project:
  type: website

website:
  title: "CityWeatherCompare"
  description: "A public site comparing weather data for multiple cities"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: table.qmd
        text: Table

format:
  html:
    css: styles.css