project:
  type: website

website:
  search: false
  title: "CityWeatherCompare"
  description: "A public site comparing weather data for multiple cities"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"

format:
  html:
    css: styles.css