---
title: "Test"
author: "Cristopher Patvakanian"
date: '2024-04-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r cars}

# Install and load required packages
# install.packages("httr")
# install.packages("jsonlite")
library(httr)
library(jsonlite)

# Define the API endpoint and parameters
api_endpoint <- "https://emvnh9buoh.execute-api.us-east-1.amazonaws.com/getData"
device_id <- 8
start_time <- "2023-11-10"
end_time <- "2024-1-8"

# Construct the URL
url <- paste0(api_endpoint, "?device_id=", device_id, "&start_time=", start_time, "&end_time=", end_time)

# Make the GET request
response <- GET(url)

# Check if the request was successful
if (http_status(response)$category == "Success") {
  # Parse the JSON response
  data <- fromJSON(content(response, "text"))
  
  # Convert data to dataframe
  dataframe <- as.data.frame(data)
  
  # Print the dataframe
  print(dataframe)
} else {
  print("Failed to retrieve data.")
}

dataframe
```


```{r}


`data-visualization_answers` <- readRDS("~/Desktop/data-visualization_answers.rds")
```

